name: example
description: Flutter Cupertino Birthday Textbox Example
version: 1.0.1

dependencies:
  cupertino_date_textbox:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
